# Generated by Django 5.0.6 on 2024-05-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_inv_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='number_in_stock',
            field=models.IntegerField(default=0),
        ),
    ]
