# Generated by Django 5.0.6 on 2024-05-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_inv_app', '0002_customerorder_total_price_vehicle_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='color',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='price',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='number_in_stock',
            field=models.PositiveIntegerField(),
        ),
    ]
